name: acquia
recipe: drupal10
config:
  webroot: docroot
  php: '8.1'
  database: mariadb:10.5


excludes:
  - vendor
  # - docroot/core
  - docroot/modules/contrib
  - docroot/profiles/contrib
  - docroot/themes/contrib
  - docroot/libraries
  - docroot/themes/custom/possibilities/node_modules
  - docroot/sites/default/files